config/routes.rb
Rails.application.routes.draw do

  root  'movies#index'

  get "/releases", to: "release_date#index"
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
  

  resources :movies
  

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

    def show
      id = params[:id] # retrieve movie ID from URI route
      @movie = Movie.find(id) # look up movie by unique ID
      # will render app/views/movies/show.<extension> by default
    end

    def list
      items_per_page - 10
      @movie = Movie.find(params[:id])
      sort = case params[:id [release_date]]
      when "title" then "title" 
      
      when "release_date" then "release_date" 
      
      when  "title_reverse" then "name DESC" 
                
      when "release_date_reverse" then "name DESC" 
                  
      end
                

      conditions =["title LIKE?", "%#{params[:id]}%"] unless params[:id].nil
      @total = movies.count(:conditions=>conditions)
      @items_pages,@movie = paginate: items, order = sort, conditions =conditions,per_page = items_per_page
      if request.xml_http_request?
        render :partial =  "movies_list", layout = false
      end
    end
  
    def index
      @movies = Movie.all
      @movies = Movie.where(nil) # creates an anonymous scope
      @movies = @movies.filter_by_rating(params[:rating]) if params[:G].present?
      @movies = @movies.filter_by_rating(params[:rating]) if params[:PG].present?
      @movies = @movies.filter_by_rating(params[:rating]) if params[:PG-13].present?
      @movies = @movies.filter_by_rating(params[:rating]) if params[:R].present?
    end
  
    def new
      # default: render 'new' template
    end
  
    def create
      @movie = Movie.create!(movie_params)
      flash[:notice] = "#{@movie.title} was successfully created."
      redirect_to movies_path
    end
  
    def edit
      @movie = Movie.find params[:id]
    end
  
    def update
      @movie = Movie.find params[:id]
      @movie.update_attributes!(movie_params)
      flash[:notice] = "#{@movie.title} was successfully updated."
      redirect_to movie_path(@movie)
    end
  
    def destroy
      @movie = Movie.find(params[:id])
      @movie.destroy
      flash[:notice] = "Movie '#{@movie.title}' deleted."
      redirect_to movies_path
    end
  
    private
    # Making "internal" methods private is not required, but is a common practice.
    # This helps make clear which methods respond to requests, and which ones do not.
    def movie_params
      params.require(:movie).permit(:title, :rating, :description, :release_date)
    end

end

app/helpers/movies_helper.rb
module MoviesHelper
  # Checks if a number is odd:
  def oddness(count)
    count.odd? ?  "odd" :  "even"
  end
end

app/views/movies/edit.html.erb
<h2>Edit Existing Movie</h2>
<%= form_tag movie_path(@movie), :method => :put do %>
  <%= label :movie, :title, 'Title', :class => 'col-form-label' %>
  <%= text_field :movie, 'title', :class => 'form-control' %>
  <%= label :movie, :rating, 'Rating', :class => 'col-form-label'  %>
  <%= select :movie, :rating, ['G','PG','PG-13','R','NC-17'], {}, {:class => 'form-control col-1'} %>
  <%= label :movie, :release_date, 'Released On', :class => 'col-form-label'  %>
  <%= date_select :movie, :release_date, {}, :class => 'form-control col-2 d-inline' %>
  <br/>
  <%= submit_tag 'Update Movie Info', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', movies_path, :class => 'btn btn-secondary' %>
<% end %>

app/views/movies/index.html.erb
<!--  This file is app/views/movies/index.html.erb -->
<h2>All Movies</h2>

<%#  Part 2: Start here... %>

<table class="table table-striped col-md-12" id="movies">
  <thead>
    <tr>
      <th>Movie Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>More Info</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td>
          <%= movie.title %>
        </td>
        <td>
          <%= movie.rating %>
        </td>
        <td>
          <%= movie.release_date %>
        </td>
        <td>
          <%= link_to "More about #{movie.title}", movie_path(movie) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if Current.user %>
    Logged in as: <%= Current.user.email %><br>
    <= link_to 'Edit Password', edit_password_path %>
    <%= button_to 'Logout', logout_path, method: :delete %>
    <% else %>
    <%= link_to 'Sign Up', sign_up_path %>
    or
    <%= link_to 'Login', sign_in_path %>
  <% end %>

<%= form_tag movies_path, :method => :get do
  Include:
  - @all_ratings.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]"
  = submit_tag 'Refresh', :class => 'btn btn-primary'

  %  >
<%= link_to 'Add new movie', new_movie_path, :class => 'btn btn-primary' %>

app/views/movies/list.html.erb
<% if @total ==0  %>>
<p> No movies...</p>
<%else %>>

<p> Number of items found : <b><%=@total %></b> </p>

<p>
<% if @items_page.page_count:>1 %>
page &nbsp;:
<%=pagation_links_remote@items_page %>
<%end %>>

</p>

<table>
   <thead>
   <tr>
   <td <% =sort_td_class_helper "title" %>>
   <% =sort_link helper "ordered_title","ordered_title" %>
   </td>
   <td <% =sort_td_class_helper "release_date" %>>
   <% =sort_link helper "ordered_release","ordered_release" %>
   </td>
   </tr>
   </thead>
   <tbody>
   <%@items.each do |i| %>
   <tr class=  "<%=cycle ("even","odd") %>">
   <td><% =i.title %><td>
   <td> <% =i.release_date %></td>
   </tr>
   <% end %>>
   </tbody>
</table>
<%end %>>

app/views/movies/new.html.erb
<h2>Create New Movie</h2>

<%= form_tag movies_path, :class => 'form' do %>
  <%= label :movie, :title, 'Title', :class => 'col-form-label' %>
  <%= text_field :movie, :title, :class => 'form-control' %>
  <%= label :movie, :rating, 'Rating', :class => 'col-form-label'  %>
  <%= select :movie, :rating, ['G','PG','PG-13','R','NC-17'], {}, {:class => 'form-control col-1'} %>
  <%= label :movie, :release_date, 'Released On', :class => 'col-form-label'  %>
  <%= date_select :movie, :release_date, {}, :class => 'form-control col-2 d-inline' %>
  <br/>
  <%= submit_tag 'Save Changes', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', movies_path, :class => 'btn btn-secondary' %>
<% end %>

app/views/movies/new_passwords.html.erb
 <h1>Forgot your password?</h1>
  <%= form_with url: password_reset_path do |f| %>
    <p>
    <%= f.label 'email:' %><br />
    <%= f.text_field :email %>
    </p>
    <p>
    <%= f.submit 'Reset Password' %>
    </p>
  <% end %>

app/views/movies/show.html.erb
<!--  app/views/movies/show.html.erb -->
<h2>
<%= link_to "odered title",movie_path(@movie)%>
Details about <em><%=@movie.title %>
</h2>

<ul id="details">
  <li>
    Rating:
    <%= @movie.rating %>
  </li>
  <li>
   <% = link_to "Ordered Releases",movie_path(@movie)%>
   Released on:
    <%= @movie.release_date.strftime("%B %d, %Y") %>
    
  </li>
</ul>

<h3>Description:</h3>
<p id="description">
  <%= @movie.description %>
</p>
<% if flash[:just_signed_up] %>
  <p class="welcome">Welcome to our movies!</p>
<% end %>


<div class="row">
  <%= link_to 'Edit', edit_movie_path(@movie), :class => 'btn btn-primary col-2' %>
  <%= link_to 'Delete', movie_path(@movie), 'data-method' => 'delete', 'data-confirm' => 'Are you sure?', :class => 'btn btn-danger col-2' %>
  <%= link_to 'Back to movie list', movies_path, :class => 'btn btn-primary col-2' %>
</div>